name: graphsage
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.5
  - tensorflow==1.15.*
  - ase==3.19.0
  - networkx==2.4
  - pandas==0.25.3
  - scikit-learn==0.22.1
  - tqdm
  - jupyterlab
  - matplotlib
  - pytest
  - pip
  - pip:
      - -e .  # The graphsage libraries in development mode
